Add MARC-Lint and Unix-Mknod to skiplst
Some modules can't be processed by cpanspec currently

        (1) updating MARC-Lint (todo 1.53 E/EI/EIJABB/MARC-Lint_1.53.tar.gz 1.52)
        CMD osc -A https://api.opensuse.org branch devel:languages:perl perl-MARC-Lint devel:languages:perl:autoupdate
        A working copy of the branched package can be checked out with:
        osc co devel:languages:perl:autoupdate/perl-MARC-Lint
        CMD wget --tries 5 --timeout 30 --connect-timeout 30 -nc -q http://cpan.metacpan.org/authors/id/E/EI/EIJABB/MARC-Lint_1.53.tar.gz -O /github/home/obs-mirror/osc/perl/MARC-Lint_1.53.tar.gz -o /dev/null
        A    devel:languages:perl:autoupdate
        A    devel:languages:perl:autoupdate/perl-MARC-Lint
        A    devel:languages:perl:autoupdate/perl-MARC-Lint/MARC-Lint_1.52.tar.gz
        A    devel:languages:perl:autoupdate/perl-MARC-Lint/perl-MARC-Lint.changes
        A    devel:languages:perl:autoupdate/perl-MARC-Lint/perl-MARC-Lint.spec
        At revision bd48e2418fe7e66ea96fbd25861099b5.
        CMD timeout 900 perl /__w/autoupdate-perl/autoupdate-perl/cpanspec/cpanspec     --dlp -v -f --pkgdetails /github/home/obs-mirror/02packages.details.txt.gz --old-file .osc/ MARC-Lint_1.53.tar.gz > cpanspec.error 2>&1
        disable executables because of Changes
        disable executables because of etc/ecbdlist.html
        disable executables because of etc/specs
        disable executables because of lib/MARC/Lint/CodeData.pm
        disable executables because of lib/MARC/Lint.pm
        disable executables because of Makefile.PL
        disable executables because of MANIFEST
        disable executables because of README
        disable executables because of t/camel.usmarc
        disable executables because of t/check020.t
        disable executables because of t/check041043.t
        disable executables because of t/check245.t
        disable executables because of t/lint.t
        disable executables because of t/test880and6.t
        Get source MARC
        Writing perl-MARC.spec...
        Use of uninitialized value $text in split at /usr/lib/perl5/vendor_perl/5.38.2/Pod/POM.pm line 177.
        Use of uninitialized value $text in pattern match (m//) at /usr/lib/perl5/vendor_perl/5.38.2/Pod/POM.pm line 193.
        # STATS # # MARC, Lint_1.53
        # STATS # ---
        # STATS # abstract:
        # STATS #   metajson: Perl extension for checking validity of MARC records
        # STATS # dynamic: 1
        # STATS # license:
        # STATS #   metajson:
        # STATS #   - unknown
        # STATS #   spec: CHECK(Artistic-1.0 or GPL-1.0-or-later)
        # STATS # metajson: 1
        # STATS # name: MARC
        # STATS # provides: 0
        # STATS # summary: Perl extension for checking validity of MARC records
        # STATS # version: Lint_1.53
        No 'provides' info in meta, parsing code.
        Invalid version format (non-numeric data) at /__w/autoupdate-perl/autoupdate-perl/cpanspec/cpanspec line 731.

        (19) updating Unix-Mknod (todo 0.05 P/PI/PIRZYK/Unix-Mknod-0.05.tar.gz 0.04)
        CMD osc -A https://api.opensuse.org branch devel:languages:perl perl-Unix-Mknod devel:languages:perl:autoupdate
        A working copy of the branched package can be checked out with:

        osc co devel:languages:perl:autoupdate/perl-Unix-Mknod
        CMD wget --tries 5 --timeout 30 --connect-timeout 30 -nc -q http://cpan.metacpan.org/authors/id/P/PI/PIRZYK/Unix-Mknod-0.05.tar.gz -O /github/home/obs-mirror/osc/perl/Unix-Mknod-0.05.tar.gz -o /dev/null
        A    devel:languages:perl:autoupdate/perl-Unix-Mknod
        A    devel:languages:perl:autoupdate/perl-Unix-Mknod/Unix-Mknod-0.04-Include-sys-sysmacros.h-on-glibc.patch
        A    devel:languages:perl:autoupdate/perl-Unix-Mknod/Unix-Mknod-0.04.tar.gz
        A    devel:languages:perl:autoupdate/perl-Unix-Mknod/cpanspec.yml
        A    devel:languages:perl:autoupdate/perl-Unix-Mknod/perl-Unix-Mknod.changes
        A    devel:languages:perl:autoupdate/perl-Unix-Mknod/perl-Unix-Mknod.spec
        At revision 184801d549ee7cd1d243dd39f11cd866.
        CMD timeout 900 perl /__w/autoupdate-perl/autoupdate-perl/cpanspec/cpanspec     --dlp -v -f --pkgdetails /github/home/obs-mirror/02packages.details.txt.gz --old-file .osc/Unix-Mknod-0.04.tar.gz Unix-Mknod-0.05.tar.gz > cpanspec.error 2>&1
        Get source Unix-Mknod
        Writing perl-Unix-Mknod.spec...

        No 'provides' info in meta, parsing code.

        dist Unix-Mknod                                           0.05 -->    v0.50.0
        module Unix::Mknod                                        0.05 -->    v0.50.0
        CMD osc addremove
        D    Unix-Mknod-0.04.tar.gz
        A    Unix-Mknod-0.05.tar.gz
        CMD osc ci -mupdate
        ERROR: Patch file Unix-Mknod-0.04-Include-sys-sysmacros.h-on-glibc.patch is zero bytes long, remove empty patch?
        Aborting: service call failed:  /usr/lib/obs/service/source_validator --outdir /github/home/obs-mirror/osc/perl/devel:languages:perl:autoupdate/perl-Unix-Mknod/tmpkvr2jqz8.source_validator.service
        A service failed with error: 1